// Quick mock to build grid without api
export const mockedProducts = [
  {
    id: "115d2aff-d262-498d-a187-585142f49e3a-B8126:en-GB",
    cultureCode: "en-GB",
    isDefaultVariant: true,
    sku: "CONBTW01",
    productName:
      "Orchard Contemporary Back-to-wall Rimless Toilet with Soft Close Seat",
    slug: "/orchard-contemporary-back-to-wall-rimless-toilet-with-soft-close-seat",
    reviewsCount: 10,
    averageRating: 3.5,
    questionsCount: 0,
    image: {
      externalId: "3ce48dc0-7b55-4c61-8c89-b01fd08c6346-B8137",
      url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/orchard-contemporary-back-to-wall-rimless-toilet-with-soft-close-seat/mainimages/conbtw01-l2.png",
      priority: 0,
      isDefault: false,
      attributes: { imageAltText: "CONBTW01-L2.png" },
    },
    stockStatus: { status: "D", stockLevel: 606 },
    price: {
      currencyCode: "GBP",
      wasPriceIncTax: 249.95,
      wasPriceExcTax: 208.29,
      priceIncTax: 139.95,
      priceExcTax: 116.63,
      isOnPromotion: true,
      discountPercentage: 44,
    },
    attributes: {},
    defaultCategory: {
      externalId: "e8332ada-f643-456c-9e32-3726b9a8d825-2986:en-GB",
      slug: "/toilets/modern-toilets",
      name: "Modern Toilets",
      isDefault: true,
      ancestors: [
        {
          slug: "/toilets",
          externalId: "6f09adc1-b19d-4a08-9029-1c5c71786026-2970:en-GB",
          name: "Toilets",
          depth: 1,
        },
      ],
    },
    brand: {
      externalId: "cceb92cf-6e35-4c4e-8105-0d8f354b2bac-3C26:en-GB",
      slug: "/brands/victorian-plumbing",
      name: "Victorian Plumbing",
      brandImage: {
        externalId: "79d9f4b7-0c3f-4427-9d4f-16377dc0c1a1-964FF",
        url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/brands/victorian-plumbing/logoimages/vplogo.png",
        priority: 100,
        isDefault: false,
        attributes: { imageAltText: "VP Logo" },
      },
    },
    score: 4.066912,
  },
  {
    id: "79d1042d-2c07-4667-8e7e-6de408259ee3-C3ED7:en-GB",
    cultureCode: "en-GB",
    isDefaultVariant: true,
    sku: "ZCC03",
    productName: "Orchard Adur Close Coupled Toilet With Soft Close Seat",
    slug: "/orchard-adur-close-coupled-toilet-with-soft-close-seat",
    averageRating: 4.7,
    reviewsCount: 3,
    questionsCount: 0,
    image: {
      externalId: "fef347e9-ee0b-4282-b6fa-3f39c9bae9fe-C3EDE",
      url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/orchard-adur-close-coupled-toilet-with-soft-close-seat/mainimages/zcc03-3.png",
      priority: 0,
      isDefault: false,
      attributes: { imageAltText: " ZCC03" },
    },
    stockStatus: { status: "D", stockLevel: 53 },
    price: {
      currencyCode: "GBP",
      wasPriceIncTax: 249.95,
      wasPriceExcTax: 208.29,
      priceIncTax: 149.95,
      priceExcTax: 124.96,
      isOnPromotion: true,
      discountPercentage: 40,
    },
    attributes: {},
    defaultCategory: {
      externalId: "a5222eb0-152c-4d05-ab5f-765e70801d9e-2976:en-GB",
      slug: "/toilets/close-coupled-toilet",
      name: "Close Coupled Toilets",
      isDefault: true,
      ancestors: [
        {
          slug: "/toilets",
          externalId: "6f09adc1-b19d-4a08-9029-1c5c71786026-2970:en-GB",
          name: "Toilets",
          depth: 1,
        },
      ],
    },
    brand: {
      externalId: "cceb92cf-6e35-4c4e-8105-0d8f354b2bac-3C26:en-GB",
      slug: "/brands/victorian-plumbing",
      name: "Victorian Plumbing",
      brandImage: {
        externalId: "79d9f4b7-0c3f-4427-9d4f-16377dc0c1a1-964FF",
        url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/brands/victorian-plumbing/logoimages/vplogo.png",
        priority: 100,
        isDefault: false,
        attributes: { imageAltText: "VP Logo" },
      },
    },
    score: 7.0201464,
  },
  {
    id: "08c956c1-a1b3-4c46-a787-0eaab2ffeed8-BE3B9:en-GB",
    cultureCode: "en-GB",
    isDefaultVariant: true,
    sku: "DECCC01SSL",
    productName:
      "Orchard Elsdon Close Coupled Toilet with Soft Close Slim Seat",
    slug: "/orchard-elsdon-close-coupled-toilet-with-soft-close-slim-seat",
    reviewsCount: 0,
    questionsCount: 0,
    image: {
      externalId: "362005c2-ce0d-497a-8e48-d3abba46f189-BE3BC",
      url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/orchard-elsdon-close-coupled-toilet-with-soft-close-slim-seat/mainimages/deccc01ssl-l32.png",
      priority: 0,
      isDefault: false,
      attributes: { imageAltText: "DECCC01SSL" },
    },
    stockStatus: { status: "D", stockLevel: 156 },
    price: {
      currencyCode: "GBP",
      wasPriceIncTax: 249.95,
      wasPriceExcTax: 208.29,
      priceIncTax: 149.95,
      priceExcTax: 124.96,
      isOnPromotion: true,
      discountPercentage: 40,
    },
    attributes: {},
    defaultCategory: {
      externalId: "a5222eb0-152c-4d05-ab5f-765e70801d9e-2976:en-GB",
      slug: "/toilets/close-coupled-toilet",
      name: "Close Coupled Toilets",
      isDefault: true,
      ancestors: [
        {
          slug: "/toilets",
          externalId: "6f09adc1-b19d-4a08-9029-1c5c71786026-2970:en-GB",
          name: "Toilets",
          depth: 1,
        },
      ],
    },
    brand: {
      externalId: "cceb92cf-6e35-4c4e-8105-0d8f354b2bac-3C26:en-GB",
      slug: "/brands/victorian-plumbing",
      name: "Victorian Plumbing",
      brandImage: {
        externalId: "79d9f4b7-0c3f-4427-9d4f-16377dc0c1a1-964FF",
        url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/brands/victorian-plumbing/logoimages/vplogo.png",
        priority: 100,
        isDefault: false,
        attributes: { imageAltText: "VP Logo" },
      },
    },
    score: 4.388257,
  },
  {
    id: "9d1aa625-325e-4b10-a828-a8d3a2d8a86b-597DE:en-GB",
    legacyId: "40081",
    legacyVariantId: "40081",
    cultureCode: "en-GB",
    isDefaultVariant: true,
    sku: "4694HR01",
    productName:
      "Villeroy and Boch Architectura DirectFlush Rimless Wall Hung Toilet + Soft Close Seat",
    slug: "/villeroy-and-boch-architectura-directflush-rimless-wall-hung-toilet-soft-close-seat-4694hr01",
    reviewsCount: 0,
    questionsCount: 0,
    image: {
      externalId: "0b8031a0-cc5d-4bc2-9e82-51172d2e54fd-597E9",
      url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/villeroy-and-boch-architectura-directflush-rimless-wall-hung-toilet-soft-close-seat-4694hr01/mainimages/4694hr01_l1.jpg",
      priority: 100,
      isDefault: false,
      attributes: {
        imageAltText:
          "Villeroy and Boch Architectura DirectFlush Rimless Wall Hung Toilet + Soft Close Seat - 4694HR01 Lar",
      },
    },
    stockStatus: { status: "G" },
    price: {
      currencyCode: "GBP",
      wasPriceIncTax: 494,
      wasPriceExcTax: 411.67,
      priceIncTax: 299.95,
      priceExcTax: 249.96,
      isOnPromotion: true,
      discountPercentage: 39,
      monthlyFinanceEstimate: 11.24,
    },
    attributes: {},
    defaultCategory: {
      externalId: "6b1b870f-ee48-4ce8-b91b-c62c3125213f-297A:en-GB",
      slug: "/toilets/wall-hung-toilets",
      name: "Wall Hung Toilets",
      isDefault: true,
      ancestors: [
        {
          slug: "/toilets",
          externalId: "6f09adc1-b19d-4a08-9029-1c5c71786026-2970:en-GB",
          name: "Toilets",
          depth: 1,
        },
      ],
    },
    brand: {
      externalId: "506bd850-d0fa-4ba2-b964-b3bfbd3622f5-3E84:en-GB",
      slug: "/brands/villeroy-and-boch",
      name: "Villeroy & Boch",
      brandImage: {
        externalId: "794b032a-06c0-454d-9f6d-be2ab9d81c2e-3E83",
        url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/brands/villeroy-and-boch/logoimages/villeroybochlogo.png",
        priority: 100,
        isDefault: false,
        attributes: { imageAltText: "Category logo image" },
      },
    },
    score: 4.5828967,
  },
  {
    id: "3dcebeac-2294-4043-868a-07e074228687-60E81:en-GB",
    legacyId: "42865",
    legacyVariantId: "42865",
    cultureCode: "en-GB",
    isDefaultVariant: true,
    sku: "VBVOBICCR",
    productName:
      "Villeroy and Boch Venticello DirectFlush Rimless BTW Close Coupled Toilet (Bottom Entry Water Inlet) + Soft Close Seat",
    slug: "/villeroy-and-boch-venticello-directflush-rimless-btw-close-coupled-toilet-bottom-entry-water-inlet-soft-close-seat",
    reviewsCount: 0,
    questionsCount: 0,
    image: {
      externalId: "c27b822b-a31f-47e3-8f25-295851e86d4f-60E9C",
      url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/villeroy-and-boch-venticello-directflush-rimless-btw-close-coupled-toilet-bottom-entry-water-inlet-soft-close-seat/mainimages/vbvosiccr_l.jpg",
      priority: 100,
      isDefault: false,
      attributes: {
        imageAltText:
          "Villeroy and Boch Venticello DirectFlush Rimless BTW Close Coupled Toilet (Bottom Entry Water Inlet)",
      },
    },
    stockStatus: { status: "G" },
    price: {
      currencyCode: "GBP",
      wasPriceIncTax: 1153.55,
      wasPriceExcTax: 961.29,
      priceIncTax: 699.95,
      priceExcTax: 583.29,
      isOnPromotion: true,
      discountPercentage: 39,
      monthlyFinanceEstimate: 26.24,
    },
    attributes: {},
    defaultCategory: {
      externalId: "df8b4d1e-abb7-4014-8d45-95ddf175a778-2982:en-GB",
      slug: "/toilets/rimless-toilets",
      name: "Rimless Toilets",
      isDefault: false,
      ancestors: [
        {
          slug: "/toilets",
          externalId: "6f09adc1-b19d-4a08-9029-1c5c71786026-2970:en-GB",
          name: "Toilets",
          depth: 1,
        },
      ],
    },
    brand: {
      externalId: "506bd850-d0fa-4ba2-b964-b3bfbd3622f5-3E84:en-GB",
      slug: "/brands/villeroy-and-boch",
      name: "Villeroy & Boch",
      brandImage: {
        externalId: "794b032a-06c0-454d-9f6d-be2ab9d81c2e-3E83",
        url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/brands/villeroy-and-boch/logoimages/villeroybochlogo.png",
        priority: 100,
        isDefault: false,
        attributes: { imageAltText: "Category logo image" },
      },
    },
    score: 2.6774316,
  },
  {
    id: "8d18201d-09d7-4ce8-a11e-a556a6d144d0-9E9B2:en-GB",
    cultureCode: "en-GB",
    isDefaultVariant: true,
    sku: "4625H201",
    productName:
      "Villeroy and Boch O.novo Combi-Pack BTW Close Coupled Toilet + Soft Close Seat",
    slug: "/villeroy-and-boch-o-novo-combi-pack-btw-close-coupled-toilet-soft-close-seat",
    averageRating: 5,
    reviewsCount: 1,
    questionsCount: 0,
    image: {
      externalId: "d0aa9512-0b05-4f7f-ac9e-6173ee3c42f7-9E9B6",
      url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/villeroy-and-boch-o-novo-combi-pack-btw-close-coupled-toilet-soft-close-seat/mainimages/4625h201.png",
      priority: 0,
      isDefault: false,
      attributes: {
        imageAltText:
          "Villeroy and Boch O.novo Combi-Pack BTW Close Coupled Toilet + Soft Close Seat",
      },
    },
    stockStatus: { status: "G" },
    price: {
      currencyCode: "GBP",
      wasPriceIncTax: 720.95,
      wasPriceExcTax: 600.79,
      priceIncTax: 449.95,
      priceExcTax: 374.96,
      isOnPromotion: true,
      discountPercentage: 38,
      monthlyFinanceEstimate: 16.87,
    },
    attributes: {},
    defaultCategory: {
      externalId: "a5222eb0-152c-4d05-ab5f-765e70801d9e-2976:en-GB",
      slug: "/toilets/close-coupled-toilet",
      name: "Close Coupled Toilets",
      isDefault: true,
      ancestors: [
        {
          slug: "/toilets",
          externalId: "6f09adc1-b19d-4a08-9029-1c5c71786026-2970:en-GB",
          name: "Toilets",
          depth: 1,
        },
      ],
    },
    brand: {
      externalId: "506bd850-d0fa-4ba2-b964-b3bfbd3622f5-3E84:en-GB",
      slug: "/brands/villeroy-and-boch",
      name: "Villeroy & Boch",
      brandImage: {
        externalId: "794b032a-06c0-454d-9f6d-be2ab9d81c2e-3E83",
        url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/brands/villeroy-and-boch/logoimages/villeroybochlogo.png",
        priority: 100,
        isDefault: false,
        attributes: { imageAltText: "Category logo image" },
      },
    },
    score: 3.9301944,
  },
  {
    id: "be7415c7-0098-4326-87a2-db765567f1df-9EE2C:en-GB",
    cultureCode: "en-GB",
    isDefaultVariant: true,
    sku: "7484B003-6342",
    productName:
      "VitrA Evi Square Wall Hung Rimless Toilet with Soft-Close Seat",
    slug: "/vitra-evi-square-wall-hung-rimless-toilet-with-soft-close-seat",
    reviewsCount: 0,
    questionsCount: 0,
    image: {
      externalId: "8e93e932-1857-4515-be51-07edf0de54e7-9EE2E",
      url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/vitra-evi-square-wall-hung-rimless-toilet-with-soft-close-seat/mainimages/7484b003-6342.png",
      priority: 0,
      isDefault: false,
      attributes: {
        imageAltText:
          "VitrA Evi Square Wall Hung Rimless Toilet with Soft-Close Seat",
      },
    },
    stockStatus: { status: "G" },
    price: {
      currencyCode: "GBP",
      wasPriceIncTax: 319.95,
      wasPriceExcTax: 266.63,
      priceIncTax: 199.95,
      priceExcTax: 166.63,
      isOnPromotion: true,
      discountPercentage: 38,
    },
    attributes: {},
    defaultCategory: {
      externalId: "e8332ada-f643-456c-9e32-3726b9a8d825-2986:en-GB",
      slug: "/toilets/modern-toilets",
      name: "Modern Toilets",
      isDefault: true,
      ancestors: [
        {
          slug: "/toilets",
          externalId: "6f09adc1-b19d-4a08-9029-1c5c71786026-2970:en-GB",
          name: "Toilets",
          depth: 1,
        },
      ],
    },
    brand: {
      externalId: "58a456a2-896d-483f-9625-e210e6d18e19-3C3A:en-GB",
      slug: "/brands/vitra",
      name: "VitrA",
      brandImage: {
        externalId: "ec83852c-8e6c-400a-abac-dca8250ef903-3C39",
        url: "https://images-nonprod.victorianplumbing.co.uk/uat/products/brands/vitra/logoimages/vitra_logo_2.jpg",
        priority: 100,
        isDefault: false,
        attributes: { imageAltText: "Category logo image" },
      },
    },
    score: 2.5904202,
  },
] as const;
